---
title: "Graphique Radars"
author: "NDubreu"
date: '2023-08-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)

```

# Diversite

```{r, echo=FALSE}
kable(resultatsDiversiteParArchipel)
```
        
```{r, echo=FALSE, fig.width=10, fig.height=10}
radarchart(
  df = diversiteSansArchipel,
  caxislabels = c(0, 1, 2, 3, 4),
  pcol = c("#00AFBB", "#E7B800", "#00008B", "#FF3300", "#7FFF00")
)

legend(
  x = 0.8,  
  legend = resultatsDiversiteParArchipel$Archipel_1, 
  bty = "n", 
  pch = 20 , 
  col = c("#00AFBB", "#E7B800", "#00008B", "#FF3300", "#7FFF00"),
  text.col = "black", 
  cex = 1, 
  pt.cex = 1.5
)
```


# Synergie

```{r, echo=FALSE}
kable(resultatsSynergiesParArchipel)
```

```{r, echo=FALSE, fig.width=10, fig.height=10}
radarchart(
  df = synergieSansArchipel,
  caxislabels = c(0, 1, 2, 3, 4),
  pcol = c("#00AFBB", "#E7B800", "#00008B", "#FF3300", "#7FFF00")
)

legend(
  x = 0.8,  
  legend = resultatsSynergiesParArchipel$Archipel_1, 
  bty = "n", 
  pch = 20 , 
  col = c("#00AFBB", "#E7B800", "#00008B", "#FF3300", "#7FFF00"),
  text.col = "black", 
  cex = 1, 
  pt.cex = 1.5
)
```