rga23_tape <- readCSV("rga23_tape.csv")
rga23_prodVegetales <- readCSV("rga23_prodVegetales.csv")
rga23_prodAnimales <- readCSV("rga23_prodAnimales.csv")
rga23_exploitations <- readCSV("rga23_exploitations.csv")
rga23_surfacesCultures <- readCSV("rga23_surfacesCultures.csv")

source("tape/1_Diversite.R")
source("tape/2_Synergies.R")
source("tape/3_Efficience.R")
source("tape/4_Recyclage.R")
source("tape/5_Resilience.R")
source("tape/6_CultureTraditions.R")
source("tape/7_Cocreation.R")
source("tape/8_ValeursHumainesSociales.R")
source("tape/9_EconomieCirculaire.R")
